### PR TITLE
New Provider SmarterMail Latest API 8629/Used Space Information (Mail)/Mail Actions New Option Delete

### PR DESCRIPTION
**Pull request by calvinhill**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

New Provider for SmarterMail 8629 Latest API
Added Mail Actions New Option Delete (Mail Actions only visible for SmarterMail 100 Editor Control)
Added MailBox Used Space in each item in Accounts Page and Total Accounts Used Space for the space selected (only visible for SmarterMail 100 Editor Control)

----

I updated the install_db.sql and update_db.sql to have the new provider

I followed your guidelines and structure of the project for the new provider but if there is something you need me to change tell please

Its our first commit to contribute to the project so let us know if its good.

Thank you

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also note any relevant details for your test configuration.

- [x] Run Portal/Enterprise and Server in local machine
- [x] Run Portal/Enterprise and Server in Production Server with different Mail Provider and versions to check compatibility

- [x ] Built code to ensure it has no errors

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by trevorrobinson** [comment]
Hey @calvinhill ,

Thankyou for the pull request.

Is this not the SmarterMail100 provider with some fixes added? If thats the case then would it not make more sense to replace the code on the current provider to ensure there is less to maintain going forward and less confusion on which one to select?

Regards,

Trevor

**Comment by FuseCP-TRobinson** [comment]
Hey @calvinhill ,

Thankyou for the pull request.

Is this not the SmarterMail100 provider with some fixes added? If thats the case then would it not make more sense to replace the code on the current provider to ensure there is less to maintain going forward and less confusion on which one to select?

Regards,

Trevor

**Comment by calvinhill** [comment]
Hey Trevor

There was a significant change in the Smartermail API aswell a new product, we are currently changing forms including new options in groups sections that are only available for the last API version. I will commit the new options in the next few days and create a new pull request. Let me know if you need me to change anything

Best regards

**Comment by FuseCP-TRobinson** [comment]
There was a significant change between SmarterMail 10 & SmarterMail 100 moving from the legacy API.

When i check over the difference in the [SmarterMail100.cs](https://github.com/FuseCP/SolidCP/blob/master/SolidCP/Sources/SolidCP.Providers.Mail.SmarterMail100/SmarterMail100.cs) to the one you commited i dont see a huge amount of changes and mainly fixing issues in the code (Alot of the procedures are 100% the same but with added try catch).

I rather find a way to keep to as few providers as possible to cause less confusion for end users.

In the exchange provider settings for example there is a checkbox for if its X version or higher to enable some features.

**Comment by calvinhill** [comment]
Hello Trevor

I made a new provider because the API has new options/behaviour but i understand your concern. I added a file thats shows the new options in the list/groups sections for Smartermail for example Show as a room in chat for Enterprise 

I was trying to see the Exchange provider to find the checkbox version but i could not find it, can you tell me how can i apply this? In the database i saw the field DisableAutoDiscovery, is that it? 

So I would create a new field like that to enable more features for the Smartermail provider?

Thank you

**Comment by FuseCP-TRobinson** [comment]
Hey,

Exchange does it via a provider setting Ex2016CU6orhigher which can be found at this [commit](https://github.com/FuseCP/SolidCP/commit/111cd09564451287be4c3e51b1449b2fa6fccb26).

For SM its maybe be better to have a dropdown to select version and in the database record the build number rather than a bool as exchange does it. It means in the code we will do checks for higher than build number to enable extra features as im sure they will add more.

Regards,

Trevor

**Comment by FuseCP-TRobinson** [comment]
Hey @calvinhill 

Just wanted to check if you was able to make progress on this?

Regards,

Trevor

**Comment by FuseCP-TRobinson** [comment]
Closing Request.

CLA not signed so code cannot be worked on without issues. to fix the issues discussed. If you are working on this still please resubmit the code with the CLA.

**Pull request closed without merging**
