### PR TITLE
 [Exchange] Ability to manage Automatic replies in Mailbox Settings / HyperV Failover Cluster and etc.

### PR DESCRIPTION
**Pull request by IvanSchulz**
# Description
 **[Exchange] Ability to manage Automatic replies in Mailbox Settings**

To use new feature:
1) Enable "Automatic Replies via SolidCP" Quota in hosting plan.
2) Enable Automatic Replies in Mailbox plan
3) Go to Mailbox - Automatic replies tab.

New Quota in database added: QuotaID - 729, QuotaName - Exchange2013.AutoReply
New methods in IExchangeServer added: GetMailboxAutoReplySettings, SetMailboxAutoReplySettings.
New class in SolidCP.Providers.HostedSolution added: ExchangeMailboxAutoReplySettings

**[HyperV2012R2+] Ability to use Failover Cluster**
1) Go to Servers - HyperV - Failover Cluster
2) Check "Use Failover Cluster" and enter FQDN Cluster name

**[HyperV2012R2+] Minimal hard disk size for OS Template**
1) Go to Servers - HyperV - OS Templates - Advanced template settings
2) Enter VHD Disk Size in GB

**Fixes # (issue)**
#7, #17, #6

### CODE REVIEW

**Comment by IvanSchulz** [comment]
Hi, I have fixed it.

**Comment by FuseCP-TRobinson** [comment]
I have checked the rest of the commit and happy to accept this once a fix for ExchangeMailboxAutoReply.ascx.de-DE.resx has been added.

**Comment by IvanSchulz** [comment]
Hi Trevor,
the file "ExchangeMailboxAutoReply.ascx.de-DE.resx" looks without any problem. I downloaded all the code from my fork and it works after build. Can you try clean and rebuild it again?

Unbenannt

**Comment by IvanSchulz** [comment]
In line 124, position 58 is german "ß" character, but there are other .resx files with the character

**Comment by FuseCP-TRobinson** [comment]
It seems maybe the issue is caused when the diff is ran. I will accept the pull and ensure that its working fine.

**Pull request merged**
