### PR TITLE
[HyperV2012R2+] Custom PowerShell scripts / Move Mail Cleaner API to Enterprise Server

### LINKED ISSUE #48: [HyperV] Create VM without External Network enabled
**Describe the bug**
When a user doesn't have external network enabled in their hosting plan then a VM cannot be created.

**To Reproduce**
Steps to reproduce the behaviour:
1. Disable External Network in Hosting Plan
2. Try create VM

**Expected behaviour**
VM to create without an network.

**SolidCP Info**
 - SolidCP Version:  1.4.7

### PR DESCRIPTION
**Pull request by IvanSchulz**
# Description

[HyperV2012R2+] Custom PowerShell scripts
[RDS Servers] Search fixed
[RDS Servers] Bug fixed (if >10 servers on one page you can edit / delete only the first 10)
Move Mail Cleaner API to Enterprise Server (API does not work from WHMCS-Module if it in WebPortal interface only)
[HyperV] Fix #48 (Create VM without External Network enabled)
[Mail cleaner] Option to disable SSL checking

**Bugs fixed:**
#48

### Custom PowerShell scripts:

You can use your PowerShell scripts on HyperV server level. Many variables and executions points can be used to be done your custom tasks.
For example you can set up a script for creating VM network adapter ACL rules for external network:
`Configuration -> Servers -> Hyper-V -> Custom PowerShell Scripts -> Add PS Script`
Execute at: `External network configuration`
PS Script:
```
Get-VMNetworkAdapterAcl -VM $vmObject -VMNetworkAdapterName $extAdapterName | Remove-VMNetworkAdapterAcl
Add-VMNetworkAdapterAcl -VM $vmObject -VMNetworkAdapterName $extAdapterName -LocalIPAddress ANY -Direction Both -Action Deny
$i = 0
while ($i -lt $extIpAddresses.length){
   Add-VMNetworkAdapterAcl -VM $vmObject -VMNetworkAdapterName $extAdapterName -LocalIPAddress $extIpAddresses[$i] -Direction Both -Action Allow
   $i++
}
```

### CODE REVIEW

**Comment by FuseCP-TRobinson** [comment]
@IvanSchulz  For the changes to MailCleaner API call location do we not also need to make changes to WHMCS?

You can see the module calls the MailCleaner API

https://github.com/FuseCP/SolidCP/blob/464b864c61f77648c5a3c7f6fd69f16108f99c29/SolidCP.WHMCSModule/modules/servers/SolidCP/SolidCP.php#L76

**Comment by IvanSchulz** [comment]
> 
> 
> @IvanSchulz For the changes to MailCleaner API call location do we not also need to make changes to WHMCS?
> 
> You can see the module calls the MailCleaner API
> 
> https://github.com/FuseCP/SolidCP/blob/464b864c61f77648c5a3c7f6fd69f16108f99c29/SolidCP.WHMCSModule/modules/servers/SolidCP/SolidCP.php#L76

WHMCS module can add new domain, but does not delete it when you delete SolidCP account. Now it works properly via ES and I think we can delete that from the WHMCS module. I will make a commit today.

**Comment by IvanSchulz** [comment]
> 
> 
> > @IvanSchulz For the changes to MailCleaner API call location do we not also need to make changes to WHMCS?
> > You can see the module calls the MailCleaner API
> > https://github.com/FuseCP/SolidCP/blob/464b864c61f77648c5a3c7f6fd69f16108f99c29/SolidCP.WHMCSModule/modules/servers/SolidCP/SolidCP.php#L76
> 
> WHMCS module can add new domain, but does not delete it when you delete SolidCP account. Now it works properly via ES and I think we can delete that from the WHMCS module. I will make a commit today.

P.s. I think WHMCS module remove only main domain, but not any others.

**Comment by FuseCP-TRobinson** [comment]
Checking this Pull request Mail cleaner doesn't appear to allow invalid SSL.

firefox_JSI7DrYERO


Can we either allow them or make a checkbox in the provider to disable SSL checking?

**Comment by IvanSchulz** [comment]
Ah, ok. I'll see what i can do.

**Comment by FuseCP-TRobinson** [comment]
The certificate verify appears to be working. I can see the changes to the file

SolidCP/Sources/SolidCP.WebPortal/DesktopModules/SolidCP/ExchangeServer/OrganizationCreateOrganization.ascx.cs

Does now remove the dropdown when creating a new org for any unused domains. I believe the only the mailcleaner specific lines needs to be removed.

firefox_dOTnwbnjVc

**Comment by IvanSchulz** [comment]
Yes, you are right. I haven't seen that ddlDomains are still used there. I do a fix commit now.

**Comment by IvanSchulz** [comment]
If I add MailCleaner inside ExchangeServerController.AddAuthoritativeDomain & ExchangeServerController.DeleteAuthoritativeDomain, then API is called twice.
Is calling within OrganizationController.AddOrganizationDomain & OrganizationController.DeleteOrganizationDomain not enough?

API call in ServerController.cs was redundant, you are right.

**Comment by FuseCP-TRobinson** [comment]
If i read the code correctly using OrganizationController.AddOrganizationDomain this is used for all hosted org and not just Exchange right?

So if i add a domain to use with RDS it would be incorrectly added to mailcleaner using the method in the code. We should just use the calls for AuthoritativeDomain.

**Comment by IvanSchulz** [comment]
Ah ok, I got it. Then I move API call from OrganizationController to ExchangeServerController.

**Pull request merged**
