### PR TITLE
Fix for update_db.sql / Journaling mailboxes / Let's Encrypt

### PR DESCRIPTION
**Pull request by IvanSchulz**
# Description

- Use custom "SplitString" function instead of STRING_SPLIT (You can not use "STRING_SPLIT" function if database compatibility_level < 130)
- Counting journaling mailboxes space in GetExchangeOrganizationStatistics and Exchange2007.DiskSpace quota
- Show journaling mailboxes on organisation statistics page
- [Let's Encrypt] Install certificate - show error message

**Fixes # (issue)**
#37

### CODE REVIEW

**Comment by FuseCP-TRobinson** [comment]
This change requires that we go from an minimum requirement of SQL 2012 to SQL 2016?

**Comment by IvanSchulz** [comment]
No, yesterday we made an update for our productive SolidCP and had a problem with "STRING_SPLIT". Now I've replaced this function with custom and it works fine.

**Comment by IvanSchulz** [comment]
We use SQL Server 2014

**Comment by IvanSchulz** [comment]
CHARINDEX and SUBSTRING should also work with SQL 2012

**Pull request merged**
