### PR TITLE
[HyperV2012R2+] Additional HDDs for VPS / [Exchange] Journaling mailboxes

### PR DESCRIPTION
**Pull request by IvanSchulz**
# Description

[WebPortal] fix DropDown style
[HyperV2012R2+] Custom PowerShell scripts - encode special characters / run on DeleteServiceItems
[HyperV2012R2+] Additional HDDs for VPS
[Exchange] Journaling mailboxes
Remove static width styles
[LetsEncrypt] Notification email settings
[Exchange] Show and remove deleted users from Public folder permissions
[Guacamole] Property for server keyboard layout
[HyperV2012R2+] do not allow changing the VM configuration when snapshots have been taken
[HyperV2012R2+] Check VM serviceId before DeleteServiceItems
[HyperV2012R2+] Fix for "af18726" (Move clustered VM to another host if not enough memory to start) - choose a node with max available memory

**Bugs fixed:**
#49

### Additional HDDs
- To use new feature you must set new quota "Additional Hard Drives per VPS" first.
- Create a new VPS or Edit VPS Configuration -> Add HDD

### Journaling mailboxes
- Set the "Journaling Mailboxes per Organization" quota value.
- Create a new mailbox plan for journaling mailboxes
- Hosted Organization - Exchange ->  Journaling Mailboxes -> New Journaling Mailbox

### CODE REVIEW

**Comment by FuseCP-MTiggelaar** [comment]
Thank you for your commit Ivan.
However i see you got static width styles.. 
can you adapt this into bootstrap type classes ? (portal still runs on bootstrap 3: https://getbootstrap.com/docs/3.3/examples/grid/ ) 

In general width should be using a Class not a style (as a style can never be responsive to screen width).
our default theme uses col by 12. (bootstrap v3)
for example: col-xs-4 / col-xs-8
or: col-md-9 / col-md-3.

You could also create custom classes in a css.. but in any case please avoid using style tags.

**Comment by IvanSchulz** [comment]
Hi Marco,
can i not use style "min-width"? I've noticed that some panels are displaying incorrectly when width is less than 480 px.
Or do you mean "Width" property like `<asp: DropDownList ID="ddlCpu" runat="server" CssClass="HugeTextBox" Width="80">`?

**Comment by FuseCP-MTiggelaar** [comment]
You can use it but it's generally best to not hardcode this. it could break custom themes, but most importantly in the future when we make theme changes custom widths and styles can become quite difficult to track down and adjust one by one.

therefor it's best to always use css classes (and for responsive grid it's normally best to use existing bootstrap values as it makes it automatically suiteable for mobile / tablet / desktops etc).

**Comment by IvanSchulz** [comment]
Ok I understand. I'll do a fix commit later.

I still have a commit with Journaling Mailbox for Exchange. Can I add that to this pull request?

**Comment by FuseCP-MTiggelaar** [comment]
Alright thank you.
And yeah it should be fine to add it to this pull request.

**Pull request merged**
